# Site settings
title: Abdelmajid Essofi
description: Academic webpage of Abdelmajid Essofi
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Abdelmajid Essofi<br/>
    Research Assistant<br/>
    Mohamed Bin Zayed University of Artificial Intelligence

location: >
  214 Solar Building, Masdar City<br/>
  Abu Dhabi, UAE

contact: >
    <a><i class="fa fa-envelope fa-1x"></i> abdelmajid.essofi@mbzuai.ac.ae</a> <br/>
    <a href="https://www.linkedin.com/in/abdelmajid-essofi-849987123/"><i class="fa fa-linkedin fa-1x"></i>  LinkedIn Page</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: research
  - name: software
  - name: team

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
